on:
  push:
    branche: 
      - master




jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v3

      - name: 'login'
        run: docker login --username ${{ secrets.USERNAME }} --password ${{ secrets.TOKEN }}

      - name: 'Image'
        run: docker build -t ${{ secrets.USERNAME }}/firstimage .

      - name: 'Docker Hub'
        run: docker push ${{ secrets.USERNAME }}/firstimage